# The index of the UART module And its pins (e.g. '1.5')
LIBMSPUARTLINK0_UART_IDX ?=
LIBMSPUARTLINK0_PIN_RX ?= 
LIBMSPUARTLINK0_PIN_TX ?= 

# Baudrate to configure the UART to
LIBMSPUARTLINK0_BAUDRATE ?= 115200

# Clock source for UART
LIBMSPUARTLINK0_CLOCK ?= SMCLK


# The index of the UART module And its pins (e.g. '1.5')
LIBMSPUARTLINK1_UART_IDX ?=
LIBMSPUARTLINK1_PIN_RX ?= 
LIBMSPUARTLINK1_PIN_TX ?= 

# Baudrate to configure the UART to
LIBMSPUARTLINK1_BAUDRATE ?= 115200

# Clock source for UART
LIBMSPUARTLINK1_CLOCK ?= SMCLK

# The index of the UART module And its pins (e.g. '1.5')
LIBMSPUARTLINK2_UART_IDX ?=
LIBMSPUARTLINK2_PIN_RX ?= 
LIBMSPUARTLINK2_PIN_TX ?= 

# Baudrate to configure the UART to
LIBMSPUARTLINK2_BAUDRATE ?= 115200

# Clock source for UART
LIBMSPUARTLINK2_CLOCK ?= SMCLK
