LIB = libmspuartlink

include ../Makefile.config
include ../Makefile.options

OBJECTS = \
	uartlink.o \

override SRC_ROOT = ../../src

override CFLAGS += \
	-I$(SRC_ROOT) \
	-I$(SRC_ROOT)/include/$(LIB) \
